### ISSUE TITLE
Inline partials are not included as a node type for rules

### ISSUE THREAD

**Issue by esmekhov** [springernature/dustmite#21]
Hi, I'm currently using this linter in one of legacy projects and I'm wondering whether the following behavior is intentional.

Dust.js has self-closing partial blocks with the following syntax
`{+foo}Hello{/foo}`

I've made a certain custom rule that requires checking references. If the reference under question is outside of `+` partial block, it is discovered by dustmite, otherwise it is ignored. Looking at the source this looks like an oversight (`+` should behave same as `<`), but maybe it isn't.

I'll attach a pull request in case this is a bug shortly.

**Comment by moddular** [comment]
Definitely an oversight. A PR would be most welcome - thank you :)
